######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 1 17:55:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .;/home/itroot/Desktop/dev/prefix/lib/include
LIBS += -L/home/itroot/Desktop/dev/prefix/lib -lcubant



# Input
HEADERS += cviz.h
SOURCES += cviz.cpp main.cpp
