######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 1 00:44:21 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cviz.h
SOURCES += cviz.cpp main.cpp
